# GEOCOVID-selectionClusters.ipynb

Selection of COVID-19 clusters for genome sequencing.

In [1]:
#LIBRARIES
import pandas as pd
import geopandas as gpd
import numpy as np
import getpass
from sqlalchemy import create_engine
import psycopg2 as ps

In [2]:
#PATHS
outdir='../outputs/cluster_selection/'

In [3]:
#CONNECT TO DB WITH user=aladoy
pw=getpass.getpass() #Ask for user password
engine=create_engine("postgresql+psycopg2://aladoy:{}@localhost/geocovid".format(pw)) #Create SQLAlchemy engine
conn=ps.connect("dbname='geocovid' user='aladoy' host='localhost' password='{}'".format(pw)) #Create a connection object
cursor=conn.cursor() #Create a cursor object

 ·········


In [4]:
#IMPORT DATA
#Genomes that were sequenced (cf. mail Damien Jacquot 16/02/2021)
sequenced=pd.read_excel('../data/df_merged_GEOCOVID-2.xlsx', engine='openpyxl')
sequenced=sequenced.drop_duplicates('id_demande')[['clusterID','startDate','endDate','observedCases','id_demande']]
sequenced=tuple(sequenced['id_demande'].tolist())
#Extract info from database (location of individuals +++)
sequenced=gpd.read_postgis("SELECT id_demande, date_reception, charge_virale, cat_charge_virale,geometry FROM covid_tests_vd WHERE id_demande IN {}".format(sequenced),conn,geom_col='geometry')
#Save to geojson
sequenced.to_file(outdir+'sequenced.geojson',driver='GeoJSON')

## Functions

In [5]:
#FUNCTION THAT RETURNS CASES WITHIN A SPECIFIC SIGNIFICANT CLUSTER THAT WERE INCLUDED IN SATSCAN ANALYSIS
#Arguments:
#   cluster_id: cluser of interest (must be significant since we didn't save backup SaTScan cases for non significant clusters)
#   save: if we want to save the results in geojson
#Outputs:
#   clusterCasesAnalysis: list of cases that were included in SaTScan analysis for the given cluster
def casesIncludedSaTScan(cluster_id, save=True):
    #Read file
    casesAnalysis=gpd.read_file('../../Part1_Description/outputs/COVID_satscan/ByRELI/ByDays/cluster_cases.gpkg')
    casesAnalysis['end_date']=pd.to_datetime(casesAnalysis.end_date)
    #Add unique ID of clusters from the database
    clustIDs=pd.read_sql_query("SELECT id, cluster, end_date FROM satscan_clusters_firstvague WHERE significant=True", conn)
    #Dataframe with significant clusters + within id_demande
    casesAnalysis=pd.merge(casesAnalysis,clustIDs, how='inner', on=['cluster','end_date'])

    #Extract cases within the cluster of interest included in SaTScan analysis
    clusterCasesAnalysis=tuple(casesAnalysis[casesAnalysis.id==cluster_id]['id_demande'].tolist())
    clusterCasesAnalysis=gpd.read_postgis("SELECT * FROM covid_tests_vd WHERE id_demande IN {}".format(clusterCasesAnalysis),conn,geom_col='geometry')

    if save==True:
        clusterCasesAnalysis.to_file(outdir+'qgis/casesAnalysis'+str(cluster_id)+'.geojson',driver='GeoJSON')

    return clusterCasesAnalysis

In [6]:
#FUNCTION THAT RETURNS CLUSTERS FOR A GIVEN AREA
#Arguments:
#   loc: desired area (name of the municipality)
#   seq: list of all sequenced individuals
#   loc_type: municipality (mun) or postal code (npa)
#Outputs:
#   optionsClust: clusters from locClust that contains at least one individual that have been already sequenced + their caracteristics (in order to select the best match)
#   casesClust: cluster and their cases (geometric intersection so not necessarly the cases included in SaTScan analyses)

def clustersLocation(loc, seq, loc_type='mun'):

    #Clusters that intersect the location
    
    if loc_type=='npa':
        sql="SELECT cl.id, cl.start_date, cl.end_date, cl.significant, cl.observed, cl.duration, cl.geometry, c.id_demande, c.note_geocoding \
        FROM (SELECT id_demande, date_reception, note_geocoding, geometry FROM covid_tests_vd WHERE res_cov=1) as c INNER JOIN \
        (SELECT s.* FROM satscan_clusters_firstvague s, npa n WHERE n.zipcode={} AND st_intersects(s.geometry, n.geometry)) cl \
        ON st_intersects(cl.geometry, c.geometry) WHERE (c.date_reception>=cl.start_date AND c.date_reception<=cl.end_date)".format(loc)
    else:
        sql="SELECT cl.id, cl.start_date, cl.end_date, cl.significant, cl.observed, cl.duration, cl.geometry, c.id_demande, c.note_geocoding \
        FROM (SELECT id_demande, date_reception, note_geocoding, geometry FROM covid_tests_vd WHERE res_cov=1) as c INNER JOIN \
        (SELECT s.* FROM satscan_clusters_firstvague s, municipalities m WHERE m.name='{}' AND st_intersects(s.geometry, m.geometry)) cl \
        ON st_intersects(cl.geometry, c.geometry) WHERE (c.date_reception>=cl.start_date AND c.date_reception<=cl.end_date)".format(loc)
    casesClust=gpd.read_postgis(sql,conn,geom_col='geometry')

    #Add dummy var for merge
    sequenced['sequenced']=1
    casesClust=pd.merge(casesClust,sequenced[['id_demande','sequenced']], how='left', on='id_demande')
    casesClust['geo_building']=np.where(casesClust.note_geocoding.str.startswith('Geocoded at building.'),1,np.nan)

    #For each cluster, compute the number of cases considered in SaTScan analysis (observed), the number of cases within cluster if we are doing a geometric intersection with residential coordinates (nb_cases)
    # including the number that are geocoded at building (nb_geoBuilding) and the number that have been already sequenced (nb_sequenced)
    optionsClust=casesClust.groupby(['id','duration','significant','observed']).agg({'id_demande':'count','geo_building':'count','sequenced':'count'}).reset_index()
    optionsClust.columns=['id','duration','significant','observed','nb_cases','nb_geoBuilding','nb_sequenced']
    optionsClust=optionsClust.sort_values('nb_sequenced',ascending=False)

    print('Number of potential clusters we can select: ' + str(optionsClust.shape[0]))
    print('Number of sequenced genomes in this area: ' + str(casesClust.drop_duplicates('id_demande').sequenced.sum()))

    return optionsClust, casesClust

In [7]:
#FUNCTION THAT RETURNS INDIVIDUALS THAT WE MUST SEQUENCED
#Arguments:
#   optionsClust: list of clusters in the desired area that already contain sequenced individuals
#   selected_cluster: id of cluster we selected in the list cluster_options
#   casesClust: cluster and their cases (geometric intersection so not necessarly the cases included in SaTScan analyses)
#Outputs:
#   finalCases: list of individuals to sequence

def ind2sequenced(optionsClust, selected_cluster, casesClust): #selected_cluster=id of the cluster we keep
    #Caracteristics of the cluster selected
    selectedClust=gpd.read_postgis("SELECT s.* FROM satscan_clusters_firstvague s WHERE s.id={}".format(selected_cluster), conn, geom_col='geometry')
    
    #If the number of cases included in SaTScan is larger than the number of cases within cluster, select the id_demande in casesAnalysis (only works for significant clusters)
    if (selectedClust.significant.all()==True) & ((optionsClust.loc[optionsClust.id==selected_cluster,'observed']>optionsClust.loc[optionsClust.id==selected_cluster,'nb_cases']).all()==True):
        #Extract cases used in SaTScan for this specific cluster
        finalCases=tuple(casesIncludedSaTScan(selected_cluster, False)['id_demande'].tolist())
        #Select more info about these cases in database
        finalCases=gpd.read_postgis("SELECT * FROM covid_tests_vd WHERE id_demande IN {}".format(finalCases),conn,geom_col='geometry')
        #Add info in the final dataframe about the cases that were already sequenced and the ones that fall outside the cluster (inside==Nan)
        finalCases=pd.merge(finalCases,casesClust[casesClust.id==selected_cluster][['id_demande','sequenced','geo_building']],how='left',on='id_demande')
        finalCases['inside']=np.where(finalCases.id_demande.isin(casesClust[casesClust.id==selected_cluster].id_demande),1,np.nan)

    else:
        finalCases=tuple(casesClust[casesClust.id==selected_cluster].id_demande.tolist())
        #Select more info about these cases in database
        finalCases=gpd.read_postgis("SELECT * FROM covid_tests_vd WHERE id_demande IN {}".format(finalCases),conn,geom_col='geometry')
        finalCases=pd.merge(finalCases,casesClust[casesClust.id==selected_cluster][['id_demande','sequenced','geo_building']],how='left',on='id_demande')
        finalCases['inside']=1
        
    print('New cases to sequence: '+str(finalCases.shape[0]-finalCases.sequenced.sum()))
    #Save file    
    finalCases.drop('geometry',axis=1).to_csv(outdir+'cases_'+str(selected_cluster)+'.csv',index=False)
    selectedClust.drop('geometry',axis=1).to_csv(outdir+'cluster_'+str(selected_cluster)+'.csv',index=False)


## Locations

### Nyon

In [23]:
optionsClustNyon, casesClustNyon= clustersLocation('Nyon', sequenced)

Number of potential clusters we can select: 64
Number of sequenced genomes in this area: 9.0


In [24]:
optionsClustNyon.head(20)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
46  794      14.0         True      22.0        19              19   
12  259       5.0         True       9.0         7               7   
30  539      10.0        False      10.0         9               9   
35  600      11.0        False      11.0        10              10   
26  486       9.0        False      12.0        10              10   
23  430       8.0        False      12.0        10              10   
39  670      12.0        False      14.0        11              11   
17  367       7.0         True       9.0         8               8   
15  336       5.0        False       9.0         9               6   
14  313       6.0         True      10.0         8               8   
43  736      13.0         True      15.0        11              11   
7   163       3.0         True       8.0         6               6   
3   105       2.0        False       4.0         3               3   
9   212       4.0         True       8.0         6               6   
11  250       5.0         True       8.0         6               6   
5   150       2.0        False       3.0         2               2   
47  797      14.0         True      11.0         7               7   
33  572      13.0        False       7.0        10               7   
8   169       2.0         True       6.0         4               4   
19  394      10.0        False       4.0         4               4   

    nb_sequenced  
46             4  
12             3  
30             3  
35             3  
26             3  
23             3  
39             3  
17             3  
15             3  
14             3  
43             3  
7              3  
3              3  
9              3  
11             2  
5              2  
47             2  
33             2  
8              2  
19             1

In [25]:
%%capture 
casesIncludedSaTScan(794,True) #to supress output for the current cell

In [26]:
ind2sequenced(optionsClustNyon, 794, casesClustNyon)

New cases to sequence: 18.0


In [27]:
optionsClustNyon[optionsClustNyon.id.isin([588,661,733])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
42  733      11.0         True       5.0         1               1   
34  588       9.0         True       5.0         1               1   
38  661      10.0         True       5.0         1               1   

    nb_sequenced  
42             0  
34             0  
38             0

Not enough individuals geocoded at the place of residence to keep this cluster.

### Vallée de Joux (Le Chenit)

In [59]:
optionsClustJoux, casesClustJoux= clustersLocation('Le Chenit', sequenced)

Number of potential clusters we can select: 27
Number of sequenced genomes in this area: 9.0


In [60]:
optionsClustJoux.head(15)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
13  352       9.0         True      35.0        34              27   
10  201       9.0         True      25.0        24              18   
18  644      14.0         True      43.0        44              36   
17  574      13.0         True      41.0        42              34   
16  514      12.0         True      38.0        37              30   
15  461      11.0         True      36.0        35              28   
14  411      10.0         True      36.0        35              28   
12  298       8.0         True      30.0        29              23   
11  246       7.0         True      28.0        27              21   
9   156       8.0         True      17.0        15              10   
8   116       7.0         True      16.0        14              10   
19  714      14.0         True      41.0        42              35   
7    91       6.0         True      10.0         9               8   
5    66       5.0         True       8.0         7               6   
20  781      14.0         True      40.0        40              35   

    nb_sequenced  
13             7  
10             7  
18             7  
17             7  
16             7  
15             7  
14             7  
12             7  
11             7  
9              5  
8              5  
19             5  
7              4  
5              3  
20             3

In [61]:
casesIncludedJoux=casesIncludedSaTScan(514,True)

n°514 because max number of already sequenced genomes, longer cluster before it starts to grow a lot


![Cluster Joux](../outputs/cluster_selection/qgis/ClusterJoux.jpg)



In [62]:
ind2sequenced(optionsClustJoux, 514, casesClustJoux)

New cases to sequence: 31.0


### Morges

In [19]:
optionsClustMorges, casesClustMorges= clustersLocation('Morges', sequenced)

Number of potential clusters we can select: 84
Number of sequenced genomes in this area: 2.0


In [20]:
optionsClustMorges.head(25)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
14   316       5.0         True      11.0        10               8   
28   596      10.0        False      17.0        17              11   
32   676      11.0        False      17.0        17              11   
25   532       9.0         True      16.0        15              10   
19   431       7.0        False      13.0        12               9   
16   363       6.0         True      13.0        12               9   
22   476       8.0         True      15.0        14               9   
9    190       6.0        False       6.0         5               5   
5    131       2.0        False       4.0         3               2   
6    139       5.0        False       5.0         5               5   
8    183       2.0        False       4.0         3               2   
11   226       7.0        False       8.0         7               7   
13   297       8.0        False       7.0         7               7   
61  1371      14.0         True       5.0         6               6   
0     32       2.0        False       3.0         3               3   
62  1385      14.0        False       4.0         5               5   
63  1400      12.0        False       3.0         4               4   
64  1414      13.0        False       3.0         4               4   
60  1360      13.0         True       5.0         6               6   
57  1335      12.0        False      10.0         8               6   
59  1355      13.0        False      10.0         8               6   
58  1343      12.0         True       5.0         5               5   
66  1430      14.0        False       3.0         4               4   
56  1324      11.0         True       5.0         5               5   
55  1305      10.0         True       5.0         5               5   

    nb_sequenced  
14             2  
28             2  
32             2  
25             2  
19             2  
16             2  
22             2  
9              1  
5              1  
6              1  
8              1  
11             1  
13             1  
61             0  
0              0  
62             0  
63             0  
64             0  
60             0  
57             0  
59             0  
58             0  
66             0  
56             0  
55             0

In [21]:
casesIncludedMorges=casesIncludedSaTScan(532,True)

n°532

![Cluster Morges](../outputs/cluster_selection/qgis/ClusterMorges.jpg)

In [22]:
ind2sequenced(optionsClustMorges, 532, casesClustMorges)

New cases to sequence: 14.0


Choose also n°1285 because other significant cluster, with all cases falling inside(no pb with corresponding reli), small size

In [26]:
casesIncludedMorges=casesIncludedSaTScan(1285,True)

In [27]:
ind2sequenced(optionsClustMorges, 1285, casesClustMorges)

New cases to sequence: 5.0


### Lausanne

In [8]:
optionsClustLausanne, casesClustLausanne= clustersLocation('Lausanne', sequenced)

Number of potential clusters we can select: 613
Number of sequenced genomes in this area: 54.0


In [9]:
optionsClustLausanne.sort_values('duration',ascending=False).head(20)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
180   429      14.0        False      18.0        15              13   
455  1239      14.0         True      14.0         9               9   
480  1304      14.0         True      20.0        14              14   
465  1266      14.0         True      23.0        16              16   
471  1284      14.0         True      25.0        18              18   
489  1322      14.0         True      19.0         9               9   
474  1290      14.0        False      14.0        11              11   
490  1323      14.0         True      17.0         8               8   
476  1294      14.0        False      16.0        14              14   
479  1297      14.0        False      16.0        23              16   
464  1265      14.0        False      16.0        13              13   
461  1255      14.0        False      16.0        27              11   
491  1327      14.0        False       9.0         8               8   
457  1246      14.0        False      16.0        12              12   
428  1138      14.0        False      20.0        17              17   
399  1041      14.0         True      22.0        19              19   
400  1042      14.0         True      20.0        12              12   
401  1043      14.0         True      20.0        16              16   
402  1044      14.0        False      21.0        17              17   
494  1334      14.0        False       8.0         7               7   

     nb_sequenced  
180             6  
455             0  
480             0  
465             0  
471             0  
489             0  
474             0  
490             0  
476             0  
479             0  
464             0  
461             0  
491             0  
457             0  
428             0  
399             0  
400             0  
401             0  
402             0  
494             0

Select several clusters listed below:

n°647

In [10]:
%%capture 
casesIncludedSaTScan(647,True) #to supress output for the current cell

In [11]:
ind2sequenced(optionsClustLausanne, 647, casesClustLausanne)

New cases to sequence: 19.0


n°92

In [12]:
%%capture 
casesIncludedSaTScan(92,True)

In [13]:
ind2sequenced(optionsClustLausanne, 92, casesClustLausanne)

New cases to sequence: 6.0


n°13

In [14]:
%%capture 
casesIncludedSaTScan(13,True)

In [15]:
ind2sequenced(optionsClustLausanne, 13, casesClustLausanne)

New cases to sequence: 2.0


n°414

In [16]:
%%capture 
casesIncludedSaTScan(414,True)

In [17]:
ind2sequenced(optionsClustLausanne, 414, casesClustLausanne)

New cases to sequence: 14.0


In [18]:
optionsClust1004, casesClust1004= clustersLocation(1004, sequenced, loc_type='npa')

Number of potential clusters we can select: 178
Number of sequenced genomes in this area: 7.0


In [19]:
optionsClust1004.head(10)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
62  528      13.0         True      19.0        22              12   
63  531      11.0         True      18.0        15              15   
24  196       8.0        False       7.0         7               3   
27  216       5.0        False       8.0         5               5   
49  421       9.0         True      14.0         9               9   
21  166       4.0         True       8.0         5               5   
17  142       3.0        False       5.0         4               4   
12  110       2.0        False       4.0         4               4   
1    21       4.0        False       3.0         1               1   
41  347       8.0        False       9.0         9               5   

    nb_sequenced  
62             3  
63             3  
24             3  
27             2  
49             2  
21             2  
17             2  
12             2  
1              1  
41             1

In [20]:
%%capture 
casesIncludedSaTScan(531,True)

In [21]:
ind2sequenced(optionsClustLausanne, 531, casesClustLausanne)

New cases to sequence: 15.0


In [22]:
#Cluser Avenue du Grey
optionsClust1004[optionsClust1004.id.isin([422,983,1088,915,849,782,715,651,582,522,469])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
106   915      14.0         True      26.0        23              23   
128  1088      12.0         True      20.0        27              14   
114   983      14.0         True      22.0        17              17   
98    849      14.0         True      27.0        24              24   
50    422       7.0         True      14.0        14              14   
83    715      12.0         True      25.0        23              23   
90    782      13.0         True      26.0        23              23   
56    469       8.0         True      16.0        15              15   
61    522       9.0         True      15.0        14              14   
74    651      11.0         True      19.0        15              15   
67    582      10.0         True      19.0        17              17   

     nb_sequenced  
106             0  
128             0  
114             0  
98              0  
50              0  
83              0  
90              0  
56              0  
61              0  
74              0  
67              0

In [23]:
%%capture 
casesIncludedSaTScan(422,True)

In [24]:
ind2sequenced(optionsClustLausanne, 422, casesClustLausanne)

New cases to sequence: 14.0


In [25]:
#Cluster of Avenue de Morges / Avenue d'Echallens
optionsClust1004[optionsClust1004.id.isin([728,657,663,783,793,914,848,980,985,1176,1211,1304,1322,1382,1391,1404,1417,1431,1444,1458,1470])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
105   914      14.0         True      27.0        12              12   
113   980      14.0         True      27.0        15              15   
115   985      14.0         True      20.0        31              16   
161  1382      11.0         True      16.0         8               8   
162  1391      12.0         True      21.0        11              11   
163  1404      13.0         True      21.0        11              11   
164  1417      14.0         True      23.0        13              13   
165  1431      14.0         True      22.0        13              13   
166  1444      14.0         True      17.0        12              12   
167  1458      14.0         True      16.0        12              12   
168  1470      14.0         True      14.0        10              10   
157  1322      14.0         True      19.0         9               9   
138  1176      13.0         True      14.0        10              10   
156  1304      14.0         True      20.0        14              14   
143  1211      14.0         True      14.0        10              10   
97    848      13.0         True      27.0        12              12   
76    657       9.0         True      15.0        12              12   
91    783      12.0         True      25.0        11              11   
92    793      11.0         True      16.0        12              12   
77    663      10.0         True      18.0         8               8   

     nb_sequenced  
105             0  
113             0  
115             0  
161             0  
162             0  
163             0  
164             0  
165             0  
166             0  
167             0  
168             0  
157             0  
138             0  
156             0  
143             0  
97              0  
76              0  
91              0  
92              0  
77              0

In [26]:
%%capture 
casesIncludedSaTScan(1470,True)

In [27]:
ind2sequenced(optionsClustLausanne, 1470, casesClustLausanne)

New cases to sequence: 14.0


1007

In [28]:
optionsClust1007, casesClust1007= clustersLocation(1007, sequenced, loc_type='npa')

Number of potential clusters we can select: 143
Number of sequenced genomes in this area: 10.0


In [29]:
optionsClust1007.head(20)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
36  412       5.0         True       5.0         5               5   
69  785      11.0         True       5.0         5               5   
44  499      12.0        False      14.0        13              13   
45  515       7.0         True       5.0         5               5   
43  494      14.0        False       5.0         6               6   
22  215       7.0        False      10.0         9               9   
21  211       9.0         True       5.0         6               6   
51  575       8.0         True       5.0         5               5   
55  634      14.0        False      15.0        14              14   
38  436      13.0        False       5.0         6               6   
56  645       9.0         True       5.0         5               5   
62  716      10.0         True       5.0         5               5   
15  141       7.0        False       7.0         5               5   
13  127       5.0         True       8.0         7               7   
27  260       8.0         True      12.0        11              11   
29  318      11.0        False       5.0         6               6   
74  851      12.0         True       5.0         5               5   
30  326       9.0        False      12.0        11              11   
78  917      13.0         True       5.0         5               5   
82  979      14.0         True       6.0         6               6   

    nb_sequenced  
36             3  
69             3  
44             3  
45             3  
43             3  
22             3  
21             3  
51             3  
55             3  
38             3  
56             3  
62             3  
15             3  
13             3  
27             3  
29             3  
74             3  
30             3  
78             3  
82             3

n°979

In [30]:
%%capture 
casesIncludedSaTScan(979,True)

In [31]:
ind2sequenced(optionsClustLausanne, 979, casesClustLausanne)

New cases to sequence: 3.0


In [33]:
#Dont know for this cluster (494?)
optionsClust1007[optionsClust1007.id.isin([211,258,318,376,436,494])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
43  494      14.0        False       5.0         6               6   
21  211       9.0         True       5.0         6               6   
38  436      13.0        False       5.0         6               6   
29  318      11.0        False       5.0         6               6   
33  376      12.0        False       5.0         6               6   
26  258      10.0         True       5.0         6               6   

    nb_sequenced  
43             3  
21             3  
38             3  
29             3  
33             3  
26             3

In [44]:
ind2sequenced(optionsClust1007, 494, casesClust1007)

New cases to sequence: 3.0


In [35]:
optionsClust1007[optionsClust1007.id.isin([71,127,215,260,326,372,438,499,564,634])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
44  499      12.0        False      14.0        13              13   
22  215       7.0        False      10.0         9               9   
55  634      14.0        False      15.0        14              14   
13  127       5.0         True       8.0         7               7   
27  260       8.0         True      12.0        11              11   
30  326       9.0        False      12.0        11              11   
32  372      10.0        False      14.0        13              13   
39  438      11.0        False      14.0        13              13   
50  564      13.0        False       8.0         7               7   
6    71       3.0        False       3.0         3               3   

    nb_sequenced  
44             3  
22             3  
55             3  
13             3  
27             3  
30             3  
32             3  
39             3  
50             2  
6              2

n°127 if we want a significant cluster or n°634 if we want non significant cluster

In [43]:
ind2sequenced(optionsClust1007, 634, casesClust1007)

New cases to sequence: 11.0


In [50]:
optionsClustLausanne[optionsClustLausanne.id.isin([79,113,160,206,248,300,354,416,463,519,585])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
175  416      11.0         True      19.0        16              16   
155  354      10.0         True      19.0        16              16   
133  300       9.0         True      18.0        15              15   
216  519      13.0         True      22.0        18              18   
195  463      12.0         True      21.0        18              18   
55   113       3.0        False       4.0         3               3   
37    79       2.0        False       4.0         3               3   
113  248       8.0         True      16.0        13              13   
95   206       7.0         True      13.0        10              10   
75   160       6.0         True      12.0         9               9   
243  585      14.0         True      22.0        18              18   

     nb_sequenced  
175             0  
155             0  
133             0  
216             0  
195             0  
55              0  
37              0  
113             0  
95              0  
75              0  
243             0

In [51]:
%%capture 
casesIncludedSaTScan(585,True)

In [52]:
ind2sequenced(optionsClustLausanne, 585, casesClustLausanne)

New cases to sequence: 22.0


In [54]:
optionsClustLausanne[optionsClustLausanne.id.isin([361,419,465,521,583,660,735])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
176  419       9.0         True      17.0        17              16   
218  521      11.0         True      20.0        20              19   
296  735      14.0         True      21.0        21              20   
268  660      13.0         True      21.0        21              20   
196  465      10.0         True      19.0        19              18   
242  583      12.0         True      21.0        21              20   
156  361       8.0         True      13.0        10              10   

     nb_sequenced  
176             3  
218             3  
296             3  
268             3  
196             3  
242             3  
156             2

In [55]:
%%capture 
casesIncludedSaTScan(583,True)

In [56]:
ind2sequenced(optionsClustLausanne, 583, casesClustLausanne)

New cases to sequence: 18.0


In [57]:
optionsClustLausanne[optionsClustLausanne.id.isin([1647,1648,1650,1653,1655,1657,1659,1661,1663,1666,1669,1672,1676])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
598  1647       2.0        False       3.0         3               3   
611  1676      14.0        False       3.0         3               3   
609  1672      13.0        False       3.0         3               3   
608  1669      12.0        False       3.0         3               3   
607  1666      11.0        False       3.0         3               3   
606  1663      10.0        False       3.0         3               3   
605  1661       9.0        False       3.0         3               3   
604  1659       8.0        False       3.0         3               3   
603  1657       7.0        False       3.0         3               3   
602  1655       6.0        False       3.0         3               3   
601  1653       5.0        False       3.0         3               3   
600  1650       4.0        False       3.0         3               3   
599  1648       3.0        False       3.0         3               3   

     nb_sequenced  
598             0  
611             0  
609             0  
608             0  
607             0  
606             0  
605             0  
604             0  
603             0  
602             0  
601             0  
600             0  
599             0

In [59]:
ind2sequenced(optionsClustLausanne, 1676, casesClustLausanne)

New cases to sequence: 3.0


In [ ]:
optionsClustLausanne[optionsClustLausanne.id.isin([305,365,420,527,589,654,729,791,860,925,1000,1061])]

In [62]:
%%capture 
casesIncludedSaTScan(791,True)

In [63]:
ind2sequenced(optionsClustLausanne, 791, casesClustLausanne)

New cases to sequence: 19.0


## Pully

In [8]:
optionsClustPully, casesClustPully= clustersLocation('Pully', sequenced,loc_type='mun')

Number of potential clusters we can select: 119
Number of sequenced genomes in this area: 18.0


In [9]:
optionsClustPully.sort_values('id',ascending=False).head(20)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
118  1680      14.0         True       6.0         6               6   
117  1678      13.0         True       6.0         6               6   
116  1674      12.0         True       5.0         5               5   
115  1670      11.0         True       5.0         5               5   
114  1667      10.0         True       5.0         5               5   
113  1664       9.0         True       4.0         4               4   
112  1662       8.0         True       4.0         4               4   
111  1660      14.0         True       5.0         5               5   
110  1658      13.0         True       4.0         4               4   
109  1656      12.0         True       4.0         4               4   
108  1654      11.0        False       3.0         3               3   
107  1652      14.0         True       4.0         4               4   
106  1651      13.0        False       3.0         3               3   
105  1649      12.0        False       3.0         3               3   
104  1631      14.0        False       3.0         3               3   
103  1624      14.0        False       3.0         3               3   
102  1621      14.0        False       4.0         4               4   
101  1619      13.0        False       4.0         4               4   
100  1615      12.0        False       4.0         4               4   
99   1611      11.0        False       4.0         4               4   

     nb_sequenced  
118             0  
117             0  
116             0  
115             0  
114             0  
113             0  
112             0  
111             0  
110             0  
109             0  
108             0  
107             0  
106             0  
105             0  
104             0  
103             0  
102             0  
101             0  
100             0  
99              0

In [10]:
%%capture 
casesIncludedSaTScan(1680,True)

In [11]:
ind2sequenced(optionsClustPully, 1680, casesClustPully)

New cases to sequence: 6.0


In [12]:
optionsClustPully.head(25)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
0    13       4.0         True       8.0         7               7   
22  308       9.0         True      15.0        13              13   
62  855      14.0         True      21.0        20              20   
56  790      13.0         True      20.0        19              19   
51  723      12.0         True      20.0        19              19   
44  594      14.0         True      20.0        18              18   
40  541      13.0        False      17.0        15              15   
36  479      12.0         True      17.0        15              15   
10  161      10.0         True      10.0         9               9   
11  164       6.0         True      10.0         9               9   
32  424      11.0         True      17.0        15              15   
14  207      11.0         True      10.0         9               9   
27  357      10.0         True      17.0        15              15   
47  652      14.0         True      23.0        21              21   
46  648      11.0         True      22.0        22              22   
30  379       6.0        False      11.0        10              10   
38  502       8.0        False      12.0        15              15   
17  282       4.0        False       7.0         4               4   
34  442      14.0        False      10.0         9               9   
3    76       2.0        False       3.0         3               3   
23  320       5.0        False       8.0         6               6   
50  722      14.0         True      23.0        21              21   
5    95       3.0         True       6.0         4               4   
7   122       6.0         True       9.0         8               8   
42  581      10.0         True      17.0        14              14   

    nb_sequenced  
0              6  
22             5  
62             5  
56             5  
51             5  
44             5  
40             5  
36             5  
10             5  
11             5  
32             5  
14             5  
27             5  
47             4  
46             4  
30             4  
38             4  
17             3  
34             3  
3              3  
23             3  
50             3  
5              3  
7              3  
42             3

In [13]:
%%capture 
casesIncludedSaTScan(594,True)

In [14]:
ind2sequenced(optionsClustPully, 594, casesClustPully)

New cases to sequence: 15.0


## Paudex

In [16]:
optionsClustPaudex, casesClustPaudex= clustersLocation('Paudex', sequenced,loc_type='mun')

Number of potential clusters we can select: 30
Number of sequenced genomes in this area: 6.0


In [18]:
optionsClustPaudex.head(10)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
10  723      12.0         True      20.0        19              19   
12  855      14.0         True      21.0        20              20   
11  790      13.0         True      20.0        19              19   
3   379       6.0        False      11.0        10              10   
6   502       8.0        False      12.0        15              15   
9   648      11.0         True      22.0        22              22   
2   320       5.0        False       8.0         6               6   
4   444       7.0        False      10.0         7               7   
1   282       4.0        False       7.0         4               4   
7   516       7.0         True      15.0        13              13   

    nb_sequenced  
10             5  
12             5  
11             5  
3              4  
6              4  
9              4  
2              3  
4              3  
1              3  
7              3

In [19]:
%%capture 
casesIncludedSaTScan(855,True)

In [20]:
ind2sequenced(optionsClustPaudex, 855, casesClustPaudex)

New cases to sequence: 16.0


## Blonay (first cluster)

In [21]:
optionsClustBlonay, casesClustBlonay= clustersLocation('Blonay', sequenced,loc_type='mun')

Number of potential clusters we can select: 2
Number of sequenced genomes in this area: 0.0


In [22]:
optionsClustBlonay

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
0    0       2.0         True       4.0         4               4   
1  158      14.0         True       4.0         4               4   

   nb_sequenced  
0             0  
1             0

We didn't keep this cluster (id:0) because three tests are for the same person..

## Yverdon-les-Bains

In [8]:
optionsClustYverdon, casesClustYverdon= clustersLocation('Yverdon-les-Bains', sequenced,loc_type='mun')

Number of potential clusters we can select: 40
Number of sequenced genomes in this area: 3.0


In [19]:
optionsClustYverdon.sort_values('observed',ascending=False).head(15)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
15   815      13.0        False      17.0        15              14   
12   755      12.0        False      16.0        14              13   
8    675      11.0        False      16.0        14              13   
6    619      10.0        False      14.0        13              12   
34  1161      11.0        False      14.0        11              11   
31  1108      10.0        False      14.0        11              11   
36  1207      12.0        False      14.0        11              11   
39  1275      14.0        False      13.0         9               9   
28  1068       9.0        False      13.0        10              10   
38  1244      13.0        False      13.0         9               9   
35  1183      11.0        False      13.0         9               9   
37  1218      12.0        False      13.0         9               9   
18   874       6.0        False      12.0        10              10   
14   803       5.0        False      12.0        10              10   
4    569       9.0        False      12.0        11              10   

    nb_sequenced  
15             0  
12             0  
8              0  
6              0  
34             0  
31             0  
36             0  
39             0  
28             0  
38             0  
35             0  
37             0  
18             0  
14             0  
4              0

In [32]:
%%capture 
casesIncludedSaTScan(668,True)

In [33]:
ind2sequenced(optionsClustYverdon, 668, casesClustYverdon)

New cases to sequence: 4.0


In [21]:
ind2sequenced(optionsClustYverdon, 1275, casesClustYverdon)

New cases to sequence: 9.0


## Cossonay

In [34]:
optionsClustCossonay, casesClustCossonay= clustersLocation('Cossonay', sequenced,loc_type='mun')

Number of potential clusters we can select: 18
Number of sequenced genomes in this area: 4.0


In [35]:
optionsClustCossonay.head(10)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
13  926      14.0         True      19.0        16              15   
4   355       5.0         True      14.0        13              12   
5   417       6.0         True      14.0        13              12   
6   472       7.0         True      14.0        13              12   
7   524       8.0         True      15.0        13              12   
10  730      11.0         True      18.0        15              14   
12  861      13.0         True      19.0        16              15   
9   658      10.0         True       9.0         3               3   
2   281       3.0        False       4.0         2               2   
8   584       9.0         True       9.0         3               3   

    nb_sequenced  
13             3  
4              3  
5              3  
6              3  
7              3  
10             3  
12             3  
9              2  
2              2  
8              2

In [37]:
optionsClustCossonay[optionsClustCossonay.id.isin([658,584,798,1016,1073])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
9    658      10.0         True       9.0         3               3   
8    584       9.0         True       9.0         3               3   
11   798      12.0         True       9.0         3               3   
15  1073      14.0        False       7.0         2               2   
14  1016      13.0        False       7.0         2               2   

    nb_sequenced  
9              2  
8              2  
11             2  
15             1  
14             1

In [38]:
%%capture 
casesIncludedSaTScan(472,True)

In [39]:
ind2sequenced(optionsClustCossonay, 472, casesClustCossonay)

New cases to sequence: 11.0


## Oron

In [40]:
optionsClustOron, casesClustOron= clustersLocation('Oron', sequenced,loc_type='mun')

Number of potential clusters we can select: 33
Number of sequenced genomes in this area: 3.0


In [42]:
optionsClustOron.head(10)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
11   813      12.0        False      11.0        11               8   
12   884      13.0        False      11.0        11               8   
13   934      14.0        False      12.0        12               9   
7    542       8.0        False       9.0         9               6   
8    593       9.0         True      11.0        11               8   
9    669      10.0        False      11.0        11               8   
10   740      11.0        False      11.0        11               8   
15  1052      14.0        False      12.0        12               9   
14   994      13.0        False      12.0        12               9   
5    450       6.0        False       6.0         5               4   

    nb_sequenced  
11             3  
12             3  
13             3  
7              3  
8              3  
9              3  
10             3  
15             2  
14             2  
5              2

In [43]:
ind2sequenced(optionsClustOron, 934, casesClustOron)

New cases to sequence: 9.0


## Servion

In [45]:
optionsClustServion, casesClustServion= clustersLocation('Servion', sequenced,loc_type='mun')

Number of potential clusters we can select: 30
Number of sequenced genomes in this area: 4.0


In [47]:
optionsClustServion.head(15)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
3   123       7.0         True       8.0         6               5   
4   170       8.0         True      11.0         8               7   
11  533      13.0        False       6.0         6               5   
2    98       6.0         True       7.0         5               4   
5   223       7.0        False       6.0         6               5   
6   265       8.0        False       7.0         7               6   
7   328       9.0        False       7.0         7               6   
8   360      10.0         True       6.0         6               5   
9   425      11.0         True       6.0         6               5   
10  478      12.0         True       6.0         6               5   
1    73       5.0        False       6.0         5               4   
12  601      14.0        False       6.0         6               5   
14  764      14.0        False       5.0         5               4   
0    34       3.0        False       3.0         2               2   
13  691      13.0        False       5.0         5               4   

    nb_sequenced  
3              4  
4              4  
11             3  
2              3  
5              3  
6              3  
7              3  
8              3  
9              3  
10             3  
1              3  
12             3  
14             2  
0              2  
13             2

In [48]:
%%capture 
casesIncludedSaTScan(360,True)

In [49]:
ind2sequenced(optionsClustServion, 360, casesClustServion)

New cases to sequence: 3.0


## Vallorbe

In [22]:
optionsClustVallorbe, casesClustVallorbe= clustersLocation('Vallorbe', sequenced,loc_type='mun')

Number of potential clusters we can select: 26
Number of sequenced genomes in this area: 2.0


In [23]:
optionsClustVallorbe.sort_values('duration',ascending=False).head(10)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
19  576      14.0         True      25.0        23              23   
24  964      14.0        False      12.0        12              12   
23  870      14.0        False      19.0        19              19   
22  792      14.0         True      22.0        20              20   
18  517      13.0         True      22.0        20              20   
21  724      13.0         True      22.0        20              20   
20  650      12.0         True      22.0        20              20   
16  466      12.0         True      20.0        18              18   
14  413      11.0         True      20.0        18              18   
17  481      11.0        False      14.0        10               9   

    nb_sequenced  
19             0  
24             0  
23             0  
22             0  
18             0  
21             0  
20             0  
16             0  
14             0  
17             2

In [24]:
%%capture 
casesIncludedSaTScan(792,True)

In [25]:
ind2sequenced(optionsClustVallorbe, 792, casesClustVallorbe)

New cases to sequence: 22.0


## Montanaire

In [34]:
optionsClustMontanaire, casesClustMontanaire= clustersLocation('Montanaire', sequenced,loc_type='mun')

Number of potential clusters we can select: 33
Number of sequenced genomes in this area: 3.0


In [37]:
optionsClustMontanaire.head(20)

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
20  1038      14.0         True      24.0        22              22   
13   850      11.0         True      23.0        21              21   
2    418       4.0         True      13.0        11              11   
5    577       7.0         True      18.0        16              16   
17   982      13.0         True      24.0        22              22   
7    646       8.0         True      20.0        18              18   
9    718       9.0         True      21.0        19              19   
15   916      12.0         True      24.0        22              22   
11   784      10.0         True      23.0        21              21   
1    350       2.0        False       5.0         5               5   
23  1173      14.0         True      12.0        11               8   
24  1212      13.0         True      15.0        14              10   
25  1238      14.0         True      11.0        10               7   
0    276       3.0        False       7.0         5               5   
26  1267      14.0         True      10.0         9               6   
22  1131      14.0         True      13.0        13              10   
28  1309      10.0        False      12.0        10               8   
29  1330      11.0        False      12.0        10               8   
30  1349      12.0        False      12.0        10               8   
31  1365      13.0        False      12.0        10               8   

    nb_sequenced  
20             3  
13             3  
2              3  
5              3  
17             3  
7              3  
9              3  
15             3  
11             3  
1              1  
23             0  
24             0  
25             0  
0              0  
26             0  
22             0  
28             0  
29             0  
30             0  
31             0

In [38]:
%%capture 
casesIncludedSaTScan(1131,True)

In [39]:
ind2sequenced(optionsClustMontanaire, 1131, casesClustMontanaire)

New cases to sequence: 13.0


## Bussigny

In [40]:
optionsClustBussigny, casesClustBussigny= clustersLocation('Bussigny', sequenced,loc_type='mun')

Number of potential clusters we can select: 16
Number of sequenced genomes in this area: 0.0


In [41]:
optionsClustBussigny

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
0   186       3.0        False       5.0         4               4   
1   241       2.0        False       5.0         3               3   
2   349       4.0        False       7.0         4               4   
3   406       5.0        False       8.0         5               5   
4   415       6.0         True      15.0        13              13   
5   470       7.0         True      15.0        13              13   
6   529       8.0         True      15.0        12              11   
7   578       9.0         True      19.0        17              17   
8   649      10.0         True      20.0        18              18   
9   699       9.0        False       4.0         2               2   
10  719      11.0         True      21.0        17              16   
11  776      10.0        False       4.0         2               2   
12  788      12.0         True      21.0        17              16   
13  842      11.0        False       4.0         2               2   
14  878      13.0        False      16.0        11              11   
15  947      14.0        False      16.0        11              11   

    nb_sequenced  
0              0  
1              0  
2              0  
3              0  
4              0  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0

In [42]:
%%capture 
casesIncludedSaTScan(649,True)

In [43]:
ind2sequenced(optionsClustBussigny, 649, casesClustBussigny)

New cases to sequence: 20.0


## Genolier

In [44]:
optionsClustGenolier, casesClustGenolier= clustersLocation('Genolier', sequenced,loc_type='mun')

Number of potential clusters we can select: 10
Number of sequenced genomes in this area: 3.0


In [45]:
optionsClustGenolier

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
0    9       2.0         True       3.0         3               3   
1   16       2.0         True       3.0         3               3   
2   28       3.0        False       3.0         3               3   
3   44       4.0         True       4.0         4               4   
4   70       5.0        False       4.0         4               4   
5  104       6.0        False       4.0         4               4   
6  137       7.0        False       4.0         4               4   
7  193       8.0        False       4.0         4               4   
8  230       9.0        False       5.0         5               5   
9  294      10.0        False       5.0         5               5   

   nb_sequenced  
0             3  
1             3  
2             3  
3             3  
4             3  
5             3  
6             3  
7             3  
8             3  
9             3

In [47]:
ind2sequenced(optionsClustGenolier, 230, casesClustGenolier)

New cases to sequence: 2.0


## Prilly

In [54]:
optionsClustPrilly, casesClustPrilly= clustersLocation('Prilly', sequenced,loc_type='mun')

Number of potential clusters we can select: 113
Number of sequenced genomes in this area: 4.0


In [55]:
optionsClustPrilly[optionsClustPrilly.id.isin([1582,1588,1592])]

id  duration  significant  observed  nb_cases  nb_geoBuilding  \
107  1592      14.0         True       6.0         6               6   
106  1588      13.0         True       6.0         6               6   
105  1582      12.0         True       6.0         6               6   

     nb_sequenced  
107             0  
106             0  
105             0

In [57]:
%%capture 
casesIncludedSaTScan(1592,True)

In [58]:
ind2sequenced(optionsClustPrilly, 1592, casesClustPrilly)

New cases to sequence: 6.0
